/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : Thom/Union
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_MASTEROFF                           0
#define GD_SLEEP                               1
#define GD_ABORT                               2
#define GD_SLAVEOFF                            3
#define GD_QUIT                                4

#define GDX_MASTEROFF                          0
#define GDX_SLEEP                              1
#define GDX_ABORT                              2
#define GDX_SLAVEOFF                           3
#define GDX_QUIT                               4

#define Main_CNT 5

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                  VisualInfo;
extern struct Window        *MainWnd;
extern struct Gadget        *MainGList;
extern struct Menu          *MainMenus;
extern struct Gadget        *MainGadgets[5];
extern UWORD                 MainLeft;
extern UWORD                 MainTop;
extern UWORD                 MainWidth;
extern UWORD                 MainHeight;
extern UBYTE                *MainWdt;
extern struct TextAttr      *Font, Attr;
extern UWORD                 FontX, FontY;
extern UWORD                 OffX, OffY;
extern struct IntuiText      MainIText[];
extern struct NewMenu        MainNewMenu[];
extern UWORD                 MainGTypes[];
extern struct NewGadget      MainNGad[];
extern ULONG                 MainGTags[];


extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern void MainRender( void );
extern int OpenMainWindow( void );
extern void CloseMainWindow( void );
